root_dataset: "/home/bht/Pictures/PCT_MAE_ViT_Test"
output_path: "/home/bht/Downloads/Output"
batch_size: 2
model_pretrained: "google/vit-base-patch16-224"
epochs: 2
image_size: 224
learning_rate: 0.001