training:
  model_type: "ViTMAEForPreTraining"
  model_name: "facebook/vit-mae-base"
  epochs: 4
  warmup_epochs: 2
  accum_iter: 3
  lr: 0.001
  min_lr: 0.00001
  batch_size: 8
  train_data_folder: "C:\\Users\\Acer\\PycharmProjects\\dataset\\train\\dew_a"
  output_model_folder: "model"
  log_and_image_output_folder: "logs"
