
training:

  img_size: (112,112)
  batch_size_train: 2
  batch_size_val: 2
  lr: 0.001

  train_dataset_folder: "dataset\\nose\\train"
  val_dataset_folder: "dataset\\nose\\val"
  num_epochs: 1
  log_outputs: "log_nose"
  model_output: "best_model_nose"

